remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-sitemap
  - jekyll-feed

favicon: assets/favicon.ico

# dont mess with SEO here
human_description: "What makes metal groove? An exploration of beat tracking, tempo estimation, percussive source separation, and various music analysis algorithms for rhythm."
description: ""

url: "https://metalgroove.xyz"

title: "metal-groove"

logo: "/assets/images/logo.webp"

author: "sevagh"

#logo - URL to a site-wide logo (e.g., /assets/your-company-logo.png) - If you would like the "publisher" property to be present, you must add this field to your site's configuration, during the validation of the structured data by Google Search Console, if the logo field is not validated, you will find errors inherent to the publisher in the Rich Results Testing Tool

social:
  name: Sevag H
  links:
    - https://github.com/sevagh

google_analytics: 'G-P5VPDH3M2N'
future: false
