remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-sitemap
  - jekyll-feed

favicon: assets/favicon.ico

# dont mess with SEO here
human_description: "What makes metal groove? An exploration of beat tracking, tempo estimation, percussive source separation, and various music analysis algorithms for rhythm."
description: ""

url: "https://metalgroove.xyz"

title: "What makes Metal Groove?"

author: "sevagh"

social:
  name: Sevag H
  links:
    - https://github.com/sevagh

google_analytics: 'G-P5VPDH3M2N'
future: false
